### ISSUE TITLE
Provide support to run multiple gauge tasks in parallel

### ISSUE THREAD

**Issue by saritapol13** [manupsunny/gauge-gradle-plugin#11]
I want to run multiple gauge tasks in parallel.

I had done below changes to code and its working fine. Please let me know if this can be changed in the source code on master as well?

If we change the all the private variables to protected from GaugeExtension.java file

   protected String specsDir;
    protected Boolean inParallel = false;
    protected Integer nodes;
    protected String env;
    protected String tags;
    protected String classpath;
    protected String additionalFlags;

Also in file GaugePlugin.java, 
 public final String GAUGE = "gauge";

Thanks,
Sarita

**Comment by manupsunny** [comment]
Can you give more details like what are you trying to do and what problems are you facing?

**Comment by saritapol13** [comment]
@manupsunny  We have nested folders under specs directory. We wanted to run 3 nested folder specs in parallel. For that we wanted to instantiate 3 gauge instances in parallel.  The number 3 is not fixed it could be anything from 1 to 5. What I observed is that the last folder that was picked only that information was retained in terms of specs dir and reports dir. For other 2 folders the information was not retained. When I changed the scope on the variables it worked fine.

 public void executeGaugeSpecs() throws Exception{
        String inParallel = true
        project.ext.specsDir=folderWithSpecifications
        project.ext.tags = runningTags
        //project.ext.inParallel = Boolean.parseBoolean(inParallel)
        project.ext.inParallel = "true"
        //project.ext.nodes = threads.toInteger()
        project.ext.nodes = threads
        project.ext.env= specsEnv
        project.ext.additionalFlags = '--strategy=\"lazy\"'

        tasks."gauge${gaugeTaskNo}".execute()

    }

Please let me know if you need any additional information.

Thanks,
Sarita

**Comment by manupsunny** [comment]
Hello @saritapol13 , we don;t have to modify the plugin to have multiple gauge instances. Please take a look at [this](https://github.com/manupsunny/gauge-gradle-plugin/issues/10) solution and let me know whether it solves your issue or not.

**Comment by saritapol13** [comment]
Hi @manupsunny 

The solution works great. Thank you

**Comment by manupsunny** [comment]
Thank you so much for your feedback.
