### ISSUE TITLE
Specs dir configuration is not relative to the project 

### ISSUE THREAD

**Issue by patresi** [manupsunny/gauge-gradle-plugin#12]
The configuration for the `specs`, path is relative to the path where gradle is executed, because of [this code](https://github.com/manupsunny/gauge-gradle-plugin/blob/e0c5b7e9a79d4b7e3fefb0e22f857367546c4764/plugin/src/main/java/com/thoughtworks/gauge/gradle/util/ProcessBuilderFactory.java#L113)

In a project with subprojects this can throw errors if the task is run from the base project or from the gauge sub project. Shouldn't this path be relative to the project?

**Comment by manupsunny** [comment]
Hello @patresi, thank you so much for raising this. We are in process of updating the plugin. This issue will be resolved soon.

**Comment by manupsunny** [comment]
The issue has been fixed and is available in v1.4.5. Download it from Bintray,

```
buildscript {
    repositories {
        maven {
            url  "http://dl.bintray.com/manupsunny/maven"
        }
        mavenCentral()
    }
    dependencies {
        classpath 'com.thoughtworks.gauge.gradle:gauge-gradle-plugin:1.4.5'
    }
}
```

**Comment by manupsunny** [comment]
You can find a sample project [here](https://github.com/manupsunny/gauge-gradle-sample)..

**Comment by patresi** [comment]
Thanks for the quick solution @manupsunny! Are you going to upload this version to maven central as well?

**Comment by manupsunny** [comment]
Yes. After a sanity check. You can expect it soon

**Comment by manupsunny** [comment]
Hi @patresi, the plugin has been uploaded to Maven central and is available [here](http://search.maven.org/#artifactdetails%7Ccom.thoughtworks.gauge.gradle%7Cgauge-gradle-plugin%7C1.4.5%7Cjar)
