### ISSUE TITLE
plugin does not support list of specs to execute

### ISSUE THREAD

**Issue by pvskarps** [manupsunny/gauge-gradle-plugin#18]
Currently it looks like the gradle gauge plugin only supports specifying a directory to execute specs from.  Gauge does support passing in a list of specs.  For instance with gauge you can do "gauge run specs/spec1.spec specs/spec2.spec specs/spec3.spec" to execute the 3 different specs.  If you attempt to do "gradle gauge -PspecsDir=specs/spec1.spec specs/spec2.spec specs/spec3.spec" a failure message of "Specs directory specified is not existing!"

**Comment by manupsunny** [comment]
Sorry for the late reply. This feature is in progress, you can expect to have it in the future releases..

**Comment by manupsunny** [comment]
Please use v1.7.1. See the updated readme for more info.
