### ISSUE TITLE
New release for gradle with latest gauge commands

### ISSUE THREAD

**Issue by nehashri** [manupsunny/gauge-gradle-plugin#19]
The current version of gradle does not work with latest gauge version. The latest gauge version has changed the command structure. There seems to be a fix done https://github.com/manupsunny/gauge-gradle-plugin/pull/16, but since the plugin is not released with fix builds have started to fail. Can you please release this plugin as soon as possible?

**Comment by manupsunny** [comment]
Hi Neha, Sorry for the late response. The new version of plugin has been released to Maven. Please find it [here](http://search.maven.org/#artifactdetails%7Ccom.thoughtworks.gauge.gradle%7Cgauge-gradle-plugin%7C1.5.0%7Cjar).
