### ISSUE TITLE
env is not loaded when passed to gauge gradle task

### ISSUE THREAD

**Issue by saritapol13** [manupsunny/gauge-gradle-plugin#3]
This is part from build.gradle file which has the gradle task

gauge {
    specsDir = "$project.rootDir"
    inParallel = true
    nodes = 2
    env = "gaugeConf"
    additionalFlags = '--verbose'
}

When I execute the gradle command as "gradle gauge" it fails as saying
[INFO] Executing command => [gauge, --parallel, -n, 2, --env, gaugeConf, --verbose, E:\GaugeDemo\specs\DRM]
 
**Exception:**
[INFO] Executing command => [gauge, --parallel, -n, 2, --env, gaugeConf, --verbose, E:\GaugeDemo\specs\DRM]
Failed to load env. gaugeConf environment does not exist
2016/03/01 19:00:51 Failed to load env. gaugeConf environment does not exist
com.thoughtworks.gauge.gradle.exception.GaugeExecutionFailedException
        at com.thoughtworks.gauge.gradle.GaugeTask.executeGaugeSpecs(GaugeTask.java:68)
        at com.thoughtworks.gauge.gradle.GaugeTask.gauge(GaugeTask.java:54)

When I tried executing from the command prompt as below:
gauge --env=gaugeConf --specsDir=E:\GaugeDemo\specs\DRM .. still the same issue.

But if you reverse the parameter sequence it works.
gauge --specsDir=E:\GaugeDemo\specs\DRM --env=gaugeConf  .. it works

I saw that in gradle plugin gauge-gradle-plugin:1.1.0, the command builder sequence is created the as mentioned in the error from method createGaugeCommand()

gauge --version
Gauge version: 0.3.2
Plugins
-------
html-report (2.0.0)
java (0.3.4)

Please let me know whether the sequence doesn't matter.

Thanks,
Sarita

**Comment by saritapol13** [comment]
I missed to add exception 

"[INFO] Executing command => [gauge, --parallel, -n, 2, --env, gaugeConf, --verbose, E:\GaugeDemo\specs\twist-02-DataRepositoryManagement]
Failed to load env. gaugeConf environment does not exist
2016/03/01 19:00:51 Failed to load env. gaugeConf environment does not exist
com.thoughtworks.gauge.gradle.exception.GaugeExecutionFailedException
        at com.thoughtworks.gauge.gradle.GaugeTask.executeGaugeSpecs(GaugeTask.java:68)
        at com.thoughtworks.gauge.gradle.GaugeTask.gauge(GaugeTask.java:54)
"

**Comment by manupsunny** [comment]
Hi saritapol13, unfortunately order of params does matter. This is a Gauge limitation. You can talk to our Gauge team for more information about this.

**Comment by manupsunny** [comment]
Please pass specsDir parameter as the last one always

**Comment by saritapol13** [comment]
passing specsDir as the last one worked.
