### ISSUE TITLE
Provide a template build.gradle

### ISSUE THREAD

**Issue by sriv** [manupsunny/gauge-gradle-plugin#6]
For new project setup, it would be helpful if there were a sample `build.gradle` template with basic tasks setup. There is [the documentation](http://getgauge.io/documentation/user/current/dependency_management/gradle-plugin.html) but the sample looks incomplete, ex. dependency on `gauge-java` is missing.

**Comment by manupsunny** [comment]
Sample given in documentation is complete. We don't need to add `gauge-java` dependency, because it is coming from plugin
