### ISSUE TITLE
Publish to Gradle Plugin Portal

### ISSUE THREAD

**Issue by sghill** [manupsunny/gauge-gradle-plugin#9]
It'd be great if this were available on the [Gradle Plugin Portal](https://plugins.gradle.org/). For anyone able to use the incubating plugin mechanism (added in gradle 2.1), the syntax for adding this plugin could be shortened to:

``` gradle
plugins {
    id 'com.thoughtworks.gauge' version '1.4.4'
}
```

instead of:

``` gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.thoughtworks.gauge.gradle:gauge-gradle-plugin:1.4.4'
    }
}
apply plugin: 'gauge'
```

**Comment by manupsunny** [comment]
Hi @sghill, Thank you so much for the suggestion. The plugin will be available in Gradle portal soon.

**Comment by manupsunny** [comment]
Hello @sghill, as per your suggestion, we have uploaded the plugin to Gradle portl. Find the instructions [here](https://plugins.gradle.org/plugin/com.thoughtworks.gauge).
